name: BE-Web-Application-For-Managing-Personal-Finance

x-backend: &backend
  env_file:
    - path: .env


services:
  db:
    <<: *backend
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    <<: *backend
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
