"""dodanie pola deleted w category

Revision ID: 00da9c7f1df0
Revises: b9a2ecadfc63
Create Date: 2024-12-05 13:01:53.536975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00da9c7f1df0'
down_revision: Union[str, None] = 'b9a2ecadfc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted')
    # ### end Alembic commands ###
