"""zmiana nazw pól w transaction

Revision ID: 1c6bf7668c0e
Revises: 3b07f07c897a
Create Date: 2024-12-01 12:30:45.420446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6bf7668c0e'
down_revision: Union[str, None] = '3b07f07c897a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('account_id_2', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_to_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_from_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id_2'], ['account_id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['account_id'])
    op.drop_column('transactions', 'from_account_id')
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('from_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_from_account_id_fkey', 'transactions', 'accounts', ['from_account_id'], ['account_id'])
    op.create_foreign_key('transactions_to_account_id_fkey', 'transactions', 'accounts', ['to_account_id'], ['account_id'])
    op.drop_column('transactions', 'account_id_2')
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
