"""zmiana niewymagania pola daty w tranzakcji

Revision ID: 28828e7c882a
Revises: 00da9c7f1df0
Create Date: 2024-12-05 14:23:17.419538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28828e7c882a'
down_revision: Union[str, None] = '00da9c7f1df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
