"""zmiana nazwy kolumny date na transaction_date

Revision ID: 342cb72e674d
Revises: 84b7e0df61c2
Create Date: 2025-01-16 09:46:01.936808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342cb72e674d'
down_revision: Union[str, None] = '84b7e0df61c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
