"""poprawka literówki v4

Revision ID: 36fe3e48f948
Revises: c8bbab56e8c7
Create Date: 2024-12-12 18:17:02.097918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fe3e48f948'
down_revision: Union[str, None] = 'c8bbab56e8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
