"""dodanie usuwania relacji w user

Revision ID: 3b07f07c897a
Revises: a80b71adfe3e
Create Date: 2024-11-30 15:08:09.316915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b07f07c897a'
down_revision: Union[str, None] = 'a80b71adfe3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
