"""dodanie pól z cyklicznością do transakcji

Revision ID: 54f5358e7fa6
Revises: 7e19a649cd0f
Create Date: 2024-12-08 16:29:23.530079

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f5358e7fa6'
down_revision: Union[str, None] = '7e19a649cd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_recurring_frequency = ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='recurringfrequency', create_type=False)


def upgrade() -> None:
    transaction_recurring_frequency.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('recurring_frequency', transaction_recurring_frequency, nullable=True))
    op.add_column('transactions', sa.Column('next_occurrence', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'next_occurrence')
    op.drop_column('transactions', 'recurring_frequency')
    op.drop_column('transactions', 'is_recurring')
    # ### end Alembic commands ###
