"""dodanie pola 'konto wychodzące i docelowe ' do transakcji

Revision ID: 7b031bf300e4
Revises: 384161a958ab
Create Date: 2024-11-24 17:27:55.104001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b031bf300e4'
down_revision: Union[str, None] = '384161a958ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('from_account_id', sa.Integer(), nullable=False))
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account_id'], ['account_id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['account_id'])
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['account_id'])
    op.drop_column('transactions', 'from_account_id')
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###
