"""wywalenie relacji do transakcji z usera

Revision ID: 7ba0b38e6f42
Revises: c2a49d280c8c
Create Date: 2024-11-19 19:06:58.417453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba0b38e6f42'
down_revision: Union[str, None] = 'c2a49d280c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
