"""poprawka literówki v7

Revision ID: 7c77fc272f90
Revises: 883a45cb603a
Create Date: 2024-12-12 18:24:08.699195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '7c77fc272f90'
down_revision: Union[str, None] = '883a45cb603a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_type_enum = ENUM('INCOME', 'OUTCOME', 'INTERNAL', name='transactiontype', create_type=False)
transaction_recurring_frequency = ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='recurringfrequency', create_type=False)


def upgrade() -> None:
       # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('recurring_transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_id_2', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', transaction_type_enum, nullable=False),
    sa.Column('recurring_frequency', transaction_recurring_frequency, nullable=False),
    sa.Column('next_occurrence', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['account_id_2'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recurring_transaction_id')
    )
    op.create_index(op.f('ix_recurring_transactions_recurring_transaction_id'), 'recurring_transactions', ['recurring_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_transactions_recurring_transaction_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
