"""zmiana wymagania pola daty w tranzakcji

Revision ID: 7e19a649cd0f
Revises: 28828e7c882a
Create Date: 2024-12-05 14:26:59.572210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e19a649cd0f'
down_revision: Union[str, None] = '28828e7c882a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
