"""poprawka literówki v6

Revision ID: 883a45cb603a
Revises: c0829a9ff2d9
Create Date: 2024-12-12 18:20:07.345272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883a45cb603a'
down_revision: Union[str, None] = 'c0829a9ff2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
