"""zmiana kaskadowego usuwania usera

Revision ID: 9d0fb3c4ede4
Revises: 92dcf3907ca0
Create Date: 2025-01-19 11:57:51.716214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0fb3c4ede4'
down_revision: Union[str, None] = '92dcf3907ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('budgets_user_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recurring_transactions_user_id_fkey', 'recurring_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recurring_transactions', type_='foreignkey')
    op.create_foreign_key('recurring_transactions_user_id_fkey', 'recurring_transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_user_id_fkey', 'budgets', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
