"""dodanie pola deleted w account

Revision ID: b9a2ecadfc63
Revises: 1c6bf7668c0e
Create Date: 2024-12-05 11:55:44.747560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a2ecadfc63'
down_revision: Union[str, None] = '1c6bf7668c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'deleted')
    # ### end Alembic commands ###
