"""poprawka literówki v5

Revision ID: c0829a9ff2d9
Revises: 36fe3e48f948
Create Date: 2024-12-12 18:17:45.512942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0829a9ff2d9'
down_revision: Union[str, None] = '36fe3e48f948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
