"""poprawka literówki v3

Revision ID: c8bbab56e8c7
Revises: 41aeee1e2ce3
Create Date: 2024-12-12 14:03:40.555745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bbab56e8c7'
down_revision: Union[str, None] = '41aeee1e2ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
