"""oddzielenie logiki transakcji cyklicznych od zwykłych

Revision ID: e142a4c88dee
Revises: 54f5358e7fa6
Create Date: 2024-12-12 13:56:58.677518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e142a4c88dee'
down_revision: Union[str, None] = '54f5358e7fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'recurring_frequency')
    op.drop_column('transactions', 'next_occurrence')
    op.drop_column('transactions', 'is_recurring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('next_occurrence', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('recurring_frequency', postgresql.ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='recurringfrequency'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
