"""usuniecie pola TYP do transakcji

Revision ID: f3eb3f5e0279
Revises: b46aea1ec9e8
Create Date: 2024-11-24 18:33:44.446272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3eb3f5e0279'
down_revision: Union[str, None] = 'b46aea1ec9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', postgresql.ENUM('INCOME', 'OUTCOME', 'INTERNAL', name='transactiontype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
